### ISSUE TITLE
Add a function to Delete a Record 

### ISSUE THREAD

**Issue by GeekBoySupreme** [GeekBoySupreme/mongodb-boilerplate#2]

**Comment by SohamDave08** [comment]
Hello, happy to connect over GitHub. Can you elaborate on what kind of function you're aiming to be developed? And should It be a normal function? Or a separate route for the desired operation? Talking about deletion, do you want to delete an entire record where a single field matches the value provided? Thank you for your time.

**Comment by GeekBoySupreme** [comment]
Hey,
It should be associated with a route. 
The pattern should be '/delete?id=XXXX'. Feel free to pick any field as a parameter from the model. routes.js file should give you the pattern in which you can write the function.

**Comment by SohamDave08** [comment]
Okay, thank you. Would be happy to contribute 😊

**Comment by mghizzo** [comment]
Can you assign this to me?

**Comment by aansh-01** [comment]
I am also doing it

**Comment by mghizzo** [comment]
I guess we can all do this. Not sure about that but I think it's fine.

**Comment by GeekBoySupreme** [comment]
Thanks for your interest. This is currently assigned to @SohamDave08
